### ISSUE TITLE
Great job! Question ...

### ISSUE THREAD

**Issue by highground88** [bizit524/WordClockEnglish#1]
Great job on this - after looking through about 20 different codes for a word clock, yours has been the best to modify for my use - I don't really know how to code but I've been able to pick a bit of stuff up reading through your work! Thanks!

I've forked your code and am building a 196LED (14x14) version for a gift.

Do you happen to get any small glitches / flickers? I don't think it's power related as I have a significant external source and capacitors installed, grounds tied. It looks to be the usual ESP8266 wifi interference, or timing based. Any suggestions?

I'd love to put some transition effects in but I doubt I'll get time before I have to give the present away.

**Comment by bizit524** [comment]
Hello, That sounds great for the transitions. Looking forward to seeing that. 
What do you mean small glitches/flickers? is it just one led or one whole word? or is it over all the words?
Previously I had all LED's slightly flickering/shimmering it was down to a bad USB power cord and charger. Really cheap ones chop the power up making it flicker. I even had 2 x 1000UF capacitors in series which helped it from shimmering but it still was there. Switched cable and power brick and it fixed it. 
If you're referring to just a single LED or 1 word within the whole 144 string. Then it is most likely the if then statements that it is running in to. It updates the display every second and checks all the if thens (the way I coded it is very inefficient but it works for what I need it to so I am not changing it) 
What happens in this case is it matches on an IF then that tells the LEDs to turn on then down later in the code it matches on 1 that tells the LEDs to turn off. This is a never ending cycle and will continue till you figure out which if thens are doing this. 
Luckily I have added a serial output/debugging in every if then so if you listen on the serial when running it you can see which ones are causing the issue. 
The other issue I had was with a few words not turning off on friday/saturday but would turn off on sunday. I have since fixed this and published the code 1 month ago. 
Other than that I have had 2 clocks I have given away and they have reported no issues with the exception of the above mentioned weekend bug

**Comment by bizit524** [comment]
Forgot to say, it is the standard ESP8266 wifi interface I imported the libraries for that and didn't really change anything on that. 
For the timing it reaches out to NTP servers (if I remember correctly) every 2 hours to resync the time.  If you live in the US you have to change the NTP server. Currently set to UK. There may be another place you have to change it (honestly forget it's been so long since I have worked on it) I say that because the time changes are different in US than the UK/EU they. UK/EU are 2 weeks later for time changes.

**Comment by highground88** [comment]
Thanks very much for your detailed reply, very much appreciated!

In regards to the 'glitches', they are just a few of the words/and or letters. e.g. at the moment it displays "JO IT IS TWENTY ONE TO NINE WELVE". The JO , IT and 'O'NE (just the O)  flicker alternatively (but the whole word together) and appear to be influenced by the "    delay(500);" in the void Displaytime segment. These 'IT & IS' words are between positions 186 and 195in the srtip - so right towards the end of the strips, but I have fed power from that side too at position 196 and a 1000uf capacitor. The ONE is about half way, and there are words in between that are unaffected.

So I think you are correct and it is probably the 'if' statements - I have tried my best but probably basterdised your code substantially and inappropriately :-) 

I tried enabling the debug on but didn't see any changes yet - I will have to look further into that.

I used your latest 'non-bacon' code only today so hopefully I picked up the latest fixes. Luckily enough I'm building this in Australia but I'm taking it to the UK next week, so hopefully it'll all line up with DST and timings with your NTP.

**Comment by bizit524** [comment]
Good you got it working, yet it was going to be down to you are doing a 14x14 i believe rearranging the letters I am assuming instead of mine which is 12x12. On bootup it displays the wrong time as it does not have a ds3231 as I didn't want to wire it up and I am being cheap. 

The debug was meant to (don't know if it's still working) go through the time very quickly/do a fake time so I could check all if then statements within 10 minutes instead of waiting 24 hours. 

You removed the pixel.clear which you need to get old irrelavant words to go away, but again it's within the loop which means it updates it multiple times on then off

**Comment by highground88** [comment]
Thanks again ... it's almost 5am here and I should really get some sleep! But it's looking good, everything is completed aside from this code which is 90% there, though I'm concerned I've shot myself in the foot a bit with using so many overlapping words. The more I watch it, the more intersecting words begin to get the flickers on the overlapping letters that I'm constantly asking to turn black (eg. threEight). I think there must surely be a better way than the else if statements I'm using almost exclusivly to run it... 

```
  else if (minute == 31) {
    lightup(WordNine, White);
    lightup(WordTwenty, White);
    lightup(WordHalf, Black);   
    lightup(WordTo, midblue);
    lightup(WordMinutes, White);    
    lightup(WordPast, Black); 
   }
  else if (minute == 32) {
    lightup(WordEight, White);
    lightup(WordNine, Black);
    lightup(WordTwenty, White);
    lightup(WordTo, midblue);
    lightup(WordMinutes, White);    
  }
```

**Comment by bizit524** [comment]
sorry not going to troubleshoot for you as you changed my design. As I mentioned you can troubleshoot over serial and you will be able to see via the output exactly what rule it is hitting 
Most likely it is hitting 2 rules which you will have to modify or add a nested if to do addition conditioning  For example code from the bacon one
      Serial.println("Break 1123");
it will serial output "Break 1123" that means the if then within that statement ran. So you can track it back from that. You can do Ctrl + F to find the block of if then that has the "Break" and figure out why it is hitting it

**Comment by highground88** [comment]
No problems at all, I'll keep at it! Thanks again for sharing your original code and the insights and suggestions.

**Comment by bizit524** [comment]
no worries, I would help troubleshoot if it was a bug in my code from not being forked and changed to a 14x14 grid but that's what happens when you fork code and start changing it. 
That is most likely happening because you are possibly overlapping vertical and horizontal words? 
Anyway good luck. The debug messages will help a lot. When I had bugs I was able to locate each if then and either fix it or create an additional nested if to do more processing

**Comment by bizit524** [comment]
When you're done you should post a pic of it on github, i'd love to see it!

**Comment by highground88** [comment]
Happy for the help you gave - I managed to learn a bit along the way! Probably not pretty code ... but it works!! I've added pictures and updated my repository. Thanks again!

**Comment by bizit524** [comment]
huzzaaahh!! glad you got it working. that looks awesome
